# Generated by Django 6.1.1 on 2026-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
