# Generated by Django 6.1.1 on 2026-09-08 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_scale', models.CharField(choices=[('normal', 'Normal'), ('lg', 'Grande'), ('xl', 'Muy grande')], default='normal', max_length=10)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de accesibilidad',
                'verbose_name_plural': 'Preferencias de accesibilidad',
            },
        ),
    ]
