# Generated by Django 6.1.1 on 2026-09-03 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('waiting_intake', 'Esperando intake'), ('ready', 'Lista'), ('both_present', 'Ambos presentes'), ('in_progress', 'En curso'), ('completed', 'Completada')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha/hora planificada de la teleconsulta.')),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True)),
                ('professional_joined_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin que creo la teleconsulta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_patient', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Consentimiento informado')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicamentos actuales')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
            },
        ),
    ]
