# Generated by Django 6.1.1 on 2026-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_briefing',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ai_briefing_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='symptoms',
            field=models.JSONField(blank=True, default=list, verbose_name='Síntomas confirmados'),
        ),
    ]
