# Generated by Django 6.1.1 on 2026-09-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_ai_briefing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('follow_up_needed', models.BooleanField(default=False, verbose_name='Requiere seguimiento')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Notas de seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='consultations.consultation')),
                ('created_by', models.ForeignKey(help_text='Profesional que registró el diagnóstico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
    ]
