# Generated by Django 6.1.1 on 2026-09-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='connection_issues',
            field=models.CharField(choices=[('none', 'No hubo problemas de conexión'), ('patient', 'Sí, por parte del paciente'), ('professional', 'Sí, por parte del profesional'), ('both', 'Sí, por ambas partes')], default='none', max_length=20, verbose_name='¿Hubo problemas de conexión?'),
        ),
    ]
